/*
CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS address (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userid INTEGER,
    address TEXT NOT NULL,
    FOREIGN KEY (userid) REFERENCES user(id)
);
*/